export const SET_CONTACT_LIST = 'SET_CONTACT_LIST';
export const SET_FAVORITE_CONTACTS = 'SET_FAVORITE_CONTACTS';
export const SET_ORIGINAL_CONTACTS = 'SET_ORIGINAL_CONTACTS';

export const SET_SELECTED_CONTACTS = 'SET_SELECTED_CONTACTS';
